environment: production
chdir: /home/jbc/www/allsum/current/
address: 173.255.199.137 
user: jbc 
group: jbc 
port: 8000
pid: /home/jbc/www/allsum/current/tmp/thin.pid
rackup: /home/jbc/www/allsum/current/config.ru
log: /home/jbc/www/allsum/current/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true
